server:
  port: 8083

spring:  cloud:    config:      server:        bootstrap: true
        git:          uri: https://github.com/nirakarmohanty/cloud-config-server
          default-label: main  application:    name: config-server 
management:  endpoints:    web:      exposure:        exclude: "*"