server:
  port: 8086
  
spring:  application:    name: billing-service-eureka

      
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /swagger-index.doc